[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
lib_deps =
    nrf24/RF24@^1.4.8
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SH110X@^2.1.10
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -O2